pipeline {
    agent {
        node{
            label 'maven'
        }
    }

environment{
    PATH = "/opt/apache-maven-3.9.12/bin:$PATH"
}
    
    stages {
        stage("build"){
            
            steps{
                dir('Hello-World'){
                sh 'mvn clean deploy -DskipTests'
                }

            }


        }
    }
}
